config {
    type: "incremental",
    schema: "analytics",
    name: "dim_customer_cdc",
    uniqueKey: ["customer_id"]
}

SELECT
  customer_id,
  customer_name,
  email,
  city,
  (CASE
      WHEN operation = 'D' THEN 'DELETED'
      ELSE status 
  END) AS status
  ,updated_at
FROM
  ${ref("customers_cdc")}
  ${
      when(
          incremental(), `where updated_at >= timestamp_sub(
          (select coalesce(max(updated_at),timestamp('1900-01-01')) from ${self()}),interval 2 day
        )`
      )
  }
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY updated_at DESC ) = 1
