config {
    type: "incremental",
    schema: "analytics",
    name: "fact_orders_incremental",
    uniqueKey: ["order_id"],
    bigquery : {
        partitionBy : "order_date",
        clusterBy : ["customer_id","status"]
    }
}

SELECT
  order_id,
  customer_id,
  amount,
  status,
  updated_at,
  order_date
FROM
  ${ref("stg_orders")} ${when(incremental(), `where updated_at >= timestamp_sub((select coalesce(max(updated_at),timestamp('1990-01-01')) from ${self()}),interval 2 day)`)}
